# -*- coding: utf-8 -*-
"""Ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MbaBF4F6ubLSZeSnv86G48-dCJmwePqg
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import re
import glob  # 🛠️ เครื่องมือสำหรับค้นหาและดึงทุกไฟล์ในโฟลเดอร์
import shutil
import urllib.request
from functools import reduce

import numpy as np
import pandas as pd
import joblib
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.font_manager as fm
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# =====================================================================
# 1. ตั้งค่าเส้นทางโฟลเดอร์
# =====================================================================
INPUT_FOLDER = '/content/drive/MyDrive/AI_Project/data_files'
MODEL_FOLDER = '/content/drive/MyDrive/AI_Project'

HISTORY_DATA_FILE = os.path.join(MODEL_FOLDER, 'ai_historical_dataset_3phase.csv')
MODEL_FILES = {
    phase: os.path.join(MODEL_FOLDER, f'power_ai_brain_3phase_{phase}.joblib')
    for phase in ['L1', 'L2', 'L3']
}

# =====================================================================
# 2. มาตรฐานการตรวจจับแรงดันไฟฟ้า อาคารเรียนระบบ 3 เฟส (380V)
# =====================================================================
RATED_VOLTAGE = 380.0  # แรงดันไฟมาตรฐานของอาคาร (โวลต์)

VOLTAGE_OVER_TH = RATED_VOLTAGE * 1.10  # 418V (ไฟเกิน: สูงกว่าปกติ 10%)
VOLTAGE_SAG_TH = RATED_VOLTAGE * 0.90  # 342V (ไฟตก/ไฟต่ำ: ต่ำกว่าปกติ 10%)
VOLTAGE_OUTAGE_TH = RATED_VOLTAGE * 0.15  # 57V  (ไฟดับ: แรงดันดิ่งลงจนแทบเป็นศูนย์)


def check_power_status(v, duration_sec=0):
    """
    v: ค่าแรงดันไฟฟ้าที่วัดได้ (โวลต์)
    duration_sec: ระยะเวลาที่เกิดสภาวะนั้นต่อเนื่อง (วินาที)
    """
    # 1. ไฟดับ: แรงดันไฟหาย ดิ่งต่ำกว่า 57V
    if v < VOLTAGE_OUTAGE_TH:
        return "⚫ ไฟดับ (Power Outage)"

    # 2. ไฟเกิน: แรงดันพุ่งสูงเกิน 418V
    elif v > VOLTAGE_OVER_TH:
        return "🔺 ไฟเกิน (Over Voltage)"

    # 3. ไฟตก / ไฟต่ำ: แรงดันร่วงต่ำกว่า 342V (ตัดสินจากระยะเวลา)
    elif v < VOLTAGE_SAG_TH:
        if duration_sec > 60:  # ต่ำค้างนานเกิน 1 นาที (60 วินาที)
            return "🔻 ไฟต่ำ (Undervoltage)"
        else:  # วูบลงสั้นๆ ไม่เกิน 1 นาที
            return "📉 ไฟตก (Voltage Sag)"

    # 4. ไฟปกติ: แรงดันอยู่ในช่วง 342V ถึง 418V
    return "✅ ไฟปกติ (Normal)"


# ลำดับความรุนแรง (เรียงจากอันตรายมากไปน้อย)
SEVERITY_ORDER = [
    "⚫ ไฟดับ (Power Outage)",
    "🔺 ไฟเกิน (Over Voltage)",
    "🔻 ไฟต่ำ (Undervoltage)",
    "📉 ไฟตก (Voltage Sag)",
    "✅ ไฟปกติ (Normal)",
]
SEVERITY_RANK = {status: rank for rank, status in enumerate(SEVERITY_ORDER)}

def worst_status(statuses):
    """เลือกสถานะที่แย่ที่สุดจาก list ของสถานะ 3 เฟส"""
    return min(statuses, key=lambda s: SEVERITY_RANK.get(s, len(SEVERITY_ORDER)))


# =====================================================================
# 3. อ่านไฟล์ทั้งหมด (.csv) ในโฟลเดอร์ + ตรวจสอบคอลัมน์ของแต่ละไฟล์
# =====================================================================
csv_files = glob.glob(os.path.join(INPUT_FOLDER, "*.csv"))

if not csv_files:
    raise FileNotFoundError(f"❌ ไม่พบไฟล์ .csv ใดๆ ในโฟลเดอร์ {INPUT_FOLDER} กรุณาตรวจสอบอีกครั้ง")

print(f"📂 เจอไฟล์ข้อมูลทั้งหมด {len(csv_files)} ไฟล์")

def smart_read_csv(file_path):
    """อ่าน CSV โดย separator อัตโนมัติ (รองรับทั้ง , และ ;)"""
    return  pd.read_csv(file_path, sep=None, engine='python')

TIME_KEYWORDS = ['time', 'timestamp', 'date', 'datetime', 'วันที่', 'เวลา']

def find_time_column(df):
    for col in df.columns:
        if any(kw in col.lower() for kw in TIME_KEYWORDS):
            return col
    return None

MEASURE_KEYWORDS_ORDERED = [
    ('THD_Voltage',   ['harmonic_voltage_distortion', 'thd_voltage', 'voltage_distortion']),
    ('THD_Current',   ['harmonic_current_distortion', 'thd_current', 'current_distortion']),
    ('PowerFactor',   ['power_factor', 'powerfactor']),
    ('ApparentPower', ['apparent_power', 'apparent power']),
    ('ReactivePower', ['reactive_power', 'reactive power']),
    ('RealPower',     ['real_power', 'realpower']),
    ('Voltage',       ['voltage']),
    ('Current',       ['current']),
]

def detect_measurement(filename):
    text = filename.lower()
    for standard_name, keywords in MEASURE_KEYWORDS_ORDERED:
        if any(kw in text for kw in keywords):
            return standard_name
    return None


df_list = []  # list of (fname, measurement, df)
for file_path in csv_files:
    fname = os.path.basename(file_path)
    df_each = smart_read_csv(file_path)
    tcol = find_time_column(df_each)
    if tcol is None:
        print(f"⚠️  ข้ามไฟล์ {fname}: ไม่พบคอลัมน์เวลา (คอลัมน์ที่มี: {df_each.columns.tolist()})")
        continue

    measurement = detect_measurement(fname)
    print(f"📖 {fname}\n    -> measurement={measurement}, คอลัมน์ดิบ={df_each.columns.tolist()}")

    if measurement is None:
        print(f"    ⚠️  ตรวจจับ measurement ไม่ได้ ข้ามไฟล์นี้")
        continue

    phase_cols = [c for c in df_each.columns if c != tcol]
    rename_map = {tcol: 'Timestamp'}
    for c in phase_cols:
        rename_map[c] = f"{measurement}_{c}"  # เช่น Voltage_L1, Current_L2
    df_each = df_each.rename(columns=rename_map)
    df_list.append((fname, df_each))

if not df_list:
    raise ValueError("❌ ไม่สามารถตรวจจับ measurement จากไฟล์ใดได้เลย กรุณาตรวจสอบรูปแบบชื่อไฟล์")


# =====================================================================
# 4. รวมทุกไฟล์เข้าด้วยกันตาม Timestamp
# =====================================================================
frames = [df for _, df in df_list]
df_new = reduce(
    lambda left, right: pd.merge(left, right, on='Timestamp', how='outer'),
    frames
).drop_duplicates()

print(f"\n📊 รวมข้อมูลเสร็จสิ้น! ได้ข้อมูล {len(df_new)} แถว")
print(f"   คอลัมน์ทั้งหมด: {df_new.columns.tolist()}")
# =====================================================================
# 5. แปลงทุกคอลัมน์ค่าที่วัดเป็นตัวเลข (กันปัญหา decimal comma แบบเดิม)
# =====================================================================
def to_numeric_smart(series):
    converted = pd.to_numeric(series, errors='coerce')
    if converted.notna().sum() >= series.notna().sum() * 0.9:
        return converted
    fixed = series.astype(str).str.replace(',', '.', regex=False)
    return pd.to_numeric(fixed, errors='coerce')

value_columns = [c for c in df_new.columns if c != 'Timestamp']
for col in value_columns:
    df_new[col] = to_numeric_smart(df_new[col])

# =====================================================================
# 6. ตรวจสอบว่ามีครบ Voltage/Current/PowerFactor ทั้ง 3 เฟสไหม
# =====================================================================
required_features = {}
for phase in ['L1', 'L2', 'L3']:
    v_col, i_col, pf_col = f'Voltage_{phase}', f'Current_{phase}', f'PowerFactor_{phase}'
    missing = [c for c in [v_col, i_col, pf_col] if c not in df_new.columns]
    if missing:
        raise KeyError(
            f"❌ เฟส {phase} ข้อมูลไม่ครบ ขาดคอลัมน์: {missing}\n"
            f"   คอลัมน์ที่มีทั้งหมด: {df_new.columns.tolist()}\n"
            f"   ตรวจสอบว่าไฟล์ Voltage/Current/PowerFactor ถูกตรวจจับ measurement ถูกต้องไหม (ดู log ด้านบน)"
        )
    required_features[phase] = (v_col, i_col, pf_col)

feature_cols = [c for triplet in required_features.values() for c in triplet]

before_drop = len(df_new)
df_new = df_new.dropna(subset=feature_cols)
print(f"\n🧹 ตัดแถวที่ข้อมูลไม่ครบทั้ง 3 เฟส: {before_drop} -> {len(df_new)} แถว")
current_cols = [i_col for _, i_col, _ in required_features.values()]
RATED_CURRENT = float(df_new[current_cols].stack().quantile(0.95))
CURRENT_OVERLOAD_TH = RATED_CURRENT * 1.20
print(f"ค่าอ้างอิงกระแส (P95 จากข้อมูล) = {RATED_CURRENT:.2f} A, เกณฑ์ Overload = {CURRENT_OVERLOAD_TH:.2f} A")

# =====================================================================
# 7. สร้าง Label: ตรวจทีละเฟส แล้วเลือกสถานะที่แย่ที่สุดเป็นสถานะรวม
# =====================================================================
def compute_row_label(row):
    statuses = [
        check_power_status(row[v_col])
        for v_col, i_col, pf_col in required_features.values()
    ]
    return worst_status(statuses)

def compute_row_label_per_phase(row):
    return {
        phase: check_power_status(row[v_col])
        for phase, (v_col, i_col, pf_col) in required_features.items()
    }

#แยกเฟสทั้ง 3 เฟสออกจากกันโดยเด็ดขาด -> AI ของแต่ละเฟสไม่ปนกัน
per_phase_status = df_new.apply(compute_row_label_per_phase, axis=1, result_type='expand')
per_phase_status.columns = [f'Status_{p}' for p in required_features.keys()]
df_new = pd.concat([df_new, per_phase_status], axis=1)

# ฟีเจอร์ของแต่ละเฟส แยกเป็นคนละชุด (V,I,PF เฉพาะเฟสตัวเอง) ไม่ยุ่งกับเฟสอื่น
X_new = {
    phase: df_new[list(cols)]
    for phase, cols in required_features.items()
}
for phase in required_features.keys():
    print(f"\n📊 การกระจายตัวของสถานะเฟส {phase}:")
    print(df_new[f'Status_{phase}'].value_counts())

# =====================================================================
# 8. ระบบสะสมความจำข้ามรอบการสอน
# =====================================================================
if os.path.exists(HISTORY_DATA_FILE):
    print("\n📚 พบข้อมูลในประวัติการสอนรอบก่อนๆ กำลังรวมร่างเพื่อเพิ่มความฉลาดให้ AI...")
    df_history = pd.read_csv(HISTORY_DATA_FILE)
    df_combined = pd.concat([df_history, df_new], ignore_index=True).drop_duplicates()
else:
    print("\n🆕 นี่คือการสอนรอบแรกของระบบ 3 เฟส คลังข้อมูลสะสมจะถูกสร้างขึ้นใหม่")
    df_combined = df_new

df_combined.to_csv(HISTORY_DATA_FILE, index=False)


# แยกฟีเจอร์และ label ของแต่ละเฟส (L1, L2, L3) ออกจากกันโดยเด็ดขาด คนละชุดข้อมูลเทรน
X_train = {}
y_train = {}
for phase, (v_col, i_col, pf_col) in required_features.items():
    X_train[phase] = df_combined[[v_col, i_col, pf_col]]
    y_train[phase] = df_combined.apply(
        lambda row, v=v_col: check_power_status(row[v]),
        axis=1
    )



# =====================================================================
# 9. เริ่มการสอน AI และบันทึกสมองถาวร
# =====================================================================
ai_models = {}
for phase in required_features.keys():
    print(f"\n🤖 AI เฟส {phase} กำลังเรียนรู้จากชุดข้อมูลสะสมทุกเคส รวมทั้งสิ้น {len(X_train[phase])} แถว...")

    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train[phase], y_train[phase])
    ai_models[phase] = model

    joblib.dump(model, MODEL_FILES[phase])
    print(f"💾 บันทึกความจำ AI เฟส {phase} ลงไฟล์ '{os.path.basename(MODEL_FILES[phase])}' บน Google Drive เรียบร้อยแล้ว!")

    df_new[f'AI_Detected_Status_{phase}'] = model.predict(X_new[phase])

print("\n📋 ตัวอย่างผลลัพธ์การตรวจจับความผิดปกติที่ AI แต่ละเฟสเรียนรู้ได้สำเร็จ:")

show_cols = (
    ['Timestamp'] + feature_cols
    + ['Status_L1', 'Status_L2', 'Status_L3']
    + ['AI_Detected_Status_L1', 'AI_Detected_Status_L2', 'AI_Detected_Status_L3']
)
display_df = df_new[show_cols].head(15)

try:
    from IPython.display import display
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', None)
    display(display_df)
except ImportError:
    print(display_df.to_string(index=False))

"""# ทดสอบความแม่นยำของโมเดล (Train/Test Split) 80%/20%"""

FONT_PATH = '/content/NotoSansThai-Regular.ttf'
try:
    if not os.path.exists(FONT_PATH):
        urllib.request.urlretrieve(
            'https://raw.githubusercontent.com/google/fonts/main/ofl/notosansthai/NotoSansThai%5Bwdth%2Cwght%5D.ttf',
            FONT_PATH
        )
    fm.fontManager.addfont(FONT_PATH)
    plt.rcParams['font.family'] = fm.FontProperties(fname=FONT_PATH).get_name()
except Exception as e:
    print(f"⚠️  โหลดฟอนต์ไทยไม่สำเร็จ ({e}) — หัวข้อกราฟภาษาไทยอาจแสดงเป็นกล่องเปล่า")

EMOJI_PATTERN = re.compile(
    "[\U0001F300-\U0001FAFF\U00002600-\U000027BF\U0001F000-\U0001F0FF]+",
    flags=re.UNICODE
)

print("=" * 70)
print("  ทดสอบความแม่นยำของโมเดล (Train/Test Split)")
print("=" * 70)

# แบ่งข้อมูล 80% ไปเทรน / 20% กันไว้ทดสอบ
X_te_dict = {}
y_te_dict = {}
y_pred_dict = {}
report_df_dict = {}
accuracy_dict = {}


for phase in ['L1', 'L2', 'L3']:
    print(f"\n--- เฟส {phase} ---")

    # แบ่งข้อมูล 80% ไปเทรน / 20% กันไว้ทดสอบ (แยกเฉพาะข้อมูลของเฟสนี้)
    try:
        X_tr, X_te, y_tr, y_te = train_test_split(
            X_train[phase], y_train[phase], test_size=0.2, random_state=42, stratify=y_train[phase]
        )
    except ValueError:
        # stratify ใช้ไม่ได้ถ้าบางสถานะมีข้อมูลน้อยเกินไป (น้อยกว่า 2 แถว) ตัดกลับไปแบ่งแบบสุ่มธรรมดา
        print("⚠️  บางสถานะมีข้อมูลน้อยเกินกว่าจะแบ่งแบบรักษาสัดส่วน (stratify) ได้ ใช้การแบ่งแบบสุ่มแทน")
        X_tr, X_te, y_tr, y_te = train_test_split(X_train[phase], y_train[phase], test_size=0.2, random_state=42)

    print(f"แบ่งข้อมูล {len(X_train[phase])} แถว -> เทรน {len(X_tr)} แถว, ทดสอบ {len(X_te)} แถว (โมเดลไม่เคยเห็นชุดทดสอบมาก่อน)")

    # เทรนโมเดลแยกต่างหากเฉพาะสำหรับทดสอบ (ไม่ยุ่งกับ ai_models ตัวจริงที่เซฟไว้ใช้งาน)
    test_model = RandomForestClassifier(n_estimators=100, random_state=42)
    test_model.fit(X_tr, y_tr)
    y_pred = test_model.predict(X_te)

    accuracy = accuracy_score(y_te, y_pred)
    print(f"\n✅ ความแม่นยำโดยรวมเฟส {phase} (Accuracy): {accuracy * 100:.2f}%")

    print("ความแม่นยำแยกตามสถานะ (precision/recall/f1-score):")
    report_df = pd.DataFrame(
        classification_report(y_te, y_pred, output_dict=True, zero_division=0)
    ).transpose().round(2)

    try:
        from IPython.display import display
        display(report_df)
    except ImportError:
        print(report_df.to_string())

    X_te_dict[phase] = X_te
    y_te_dict[phase] = y_te
    y_pred_dict[phase] = y_pred
    report_df_dict[phase] = report_df
    accuracy_dict[phase] = accuracy

print("\nหมายเหตุ: โมเดลที่ใช้ทดสอบในไฟล์นี้เป็นคนละตัวกับ ai_models ที่เซฟไว้ใช้งานจริง")
print("(ai_models ตัวจริงเทรนด้วยข้อมูลทั้งหมด รวมส่วนที่กันไว้ทดสอบด้วย เพื่อให้ฉลาดที่สุด)")

"""# สร้างกราฟจากผลการทดสอบจริง (Confusion Matrix + ความแม่นยำรายสถานะ)"""

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
from sklearn.metrics import confusion_matrix

import os
import shutil

"""# ต้องนิยาม clean_label ไว้ก่อนใช้งาน

# กราฟที่ 1: Confusion Matrix (ทายถูก vs ทายผิด แยกตามสถานะจริง)
"""

EMOJI_PATTERN = re.compile(
    "[\U0001F300-\U0001FAFF\U00002600-\U000027BF\U0001F000-\U0001F0FF]+",
    flags=re.UNICODE
)

def clean_label(text):
    return EMOJI_PATTERN.sub('', str(text)).strip()


FONT_PATH = '/content/NotoSansThai-Regular.ttf'
try:
    if not os.path.exists(FONT_PATH):
        urllib.request.urlretrieve(
            'https://raw.githubusercontent.com/google/fonts/main/ofl/notosansthai/NotoSansThai%5Bwdth%2Cwght%5D.ttf',
            FONT_PATH
        )
    fm.fontManager.addfont(FONT_PATH)
    plt.rcParams['font.family'] = fm.FontProperties(fname=FONT_PATH).get_name()
except Exception as e:
    print(f"⚠️  โหลดฟอนต์ไทยไม่สำเร็จ ({e}) — หัวข้อกราฟภาษาไทยอาจแสดงเป็นกล่องเปล่า")

EMOJI_PATTERN = re.compile(
    "[\U0001F300-\U0001FAFF\U00002600-\U000027BF\U0001F000-\U0001F0FF]+",
    flags=re.UNICODE
)



def clean_label_safe(text):
    text = clean_label(text)
    text = re.sub(r'[\U0000FE00-\U0000FE0F]', '', text)
    return text.strip()

confusion_matrix_filenames = []

for phase in ['L1', 'L2', 'L3']:
    y_te = y_te_dict[phase]
    y_pred = y_pred_dict[phase]

    labels_order = sorted(set(y_te) | set(y_pred))
    cm = confusion_matrix(y_te, y_pred, labels=labels_order)

    clean_labels_order = [clean_label_safe(s) for s in labels_order]
    n = len(clean_labels_order)
    row_totals = cm.sum(axis=1)

    fig, ax = plt.subplots(figsize=(1.7 * n + 3, 1.5 * n + 3))

    # แทนที่จะไล่สีน้ำเงินเฉดเดียว (ตีความยาก) ใช้ "เขียว = ทายถูก, แดง = ทายผิด"
    # ความเข้มของสีบอกสัดส่วน (%) ของแถวนั้น ทำให้เห็นปุ๊บรู้ปั๊บว่าแม่นแค่ไหน
    color_matrix = np.ones((n, n, 3))
    for row in range(n):
        for col in range(n):
            pct = cm[row, col] / row_totals[row] if row_totals[row] > 0 else 0
            if row == col:
                color_matrix[row, col] = [1 - 0.65 * pct, 1 - 0.15 * pct, 1 - 0.65 * pct]  # เขียว
            else:
                color_matrix[row, col] = [1 - 0.15 * pct, 1 - 0.65 * pct, 1 - 0.65 * pct]  # แดง

    ax.imshow(color_matrix)

    ax.set_xticks(range(n))
    ax.set_yticks(range(n))
    ax.set_xticklabels(clean_labels_order, rotation=30, ha='right', fontsize=11)
    ax.set_yticklabels(clean_labels_order, fontsize=11)
    ax.set_xlabel('สถานะที่ AI ทาย', fontsize=12)
    ax.set_ylabel('สถานะจริง', fontsize=12)
    ax.set_title(f'Confusion Matrix เฟส {phase}: เทียบสถานะจริง vs สถานะที่ AI ทาย\n(เขียว = ทายถูก, แดง = ทายผิด, สีเข้ม = สัดส่วนเยอะ)', fontsize=13)

    # เส้นตารางสีขาวคั่นแต่ละช่องให้ดูเป็นตารางชัดเจน
    ax.set_xticks(np.arange(-0.5, n, 1), minor=True)
    ax.set_yticks(np.arange(-0.5, n, 1), minor=True)
    ax.grid(which='minor', color='white', linewidth=2)
    ax.tick_params(which='minor', bottom=False, left=False)

    for row in range(n):
        for col in range(n):
            value = cm[row, col]
            pct = value / row_totals[row] * 100 if row_totals[row] > 0 else 0
            label = f"{value}\n({pct:.0f}%)" if row_totals[row] > 0 else str(value)
            ax.text(col, row, label, ha='center', va='center', fontsize=13, fontweight='bold', color='black')

    plt.tight_layout()
    fname = f'confusion_matrix_3phase_{phase}.png'
    plt.savefig(os.path.join(MODEL_FOLDER, fname), dpi=150)
    plt.show()
    confusion_matrix_filenames.append(fname)

"""# กราฟที่ 2: F1-score แยกตามสถานะ (ยิ่งใกล้ 1.0 ยิ่งแม่น)"""

# สีเขียว = แม่นมาก (>=0.9), ส้ม = พอใช้ (0.7-0.9), แดง = ต้องปรับปรุง (<0.7)
def score_color(score):
    if score >= 0.9:
        return '#3a9d43'
    elif score >= 0.7:
        return '#e8a33d'
    return '#d9534f'

f1_score_filenames = []

for phase in ['L1', 'L2', 'L3']:
    report_df = report_df_dict[phase]
    per_status_df = report_df.drop(index=['accuracy', 'macro avg', 'weighted avg'], errors='ignore')

    # เรียงจากแม่นสุด -> แย่สุด อ่านง่ายกว่าเรียงตามลำดับตัวอักษรเดิม
    per_status_df = per_status_df.sort_values('f1-score', ascending=False)
    clean_status_labels = [clean_label_safe(s) for s in per_status_df.index]

    colors = [score_color(v) for v in per_status_df['f1-score']]

    fig, ax = plt.subplots(figsize=(max(9, 1.3 * len(clean_status_labels)), 5.5))
    bars = ax.bar(clean_status_labels, per_status_df['f1-score'], color=colors)
    ax.axhline(1.0, color='gray', linestyle=':', alpha=0.6, label='แม่นยำสมบูรณ์ (1.0)')
    ax.axhline(0.9, color='#3a9d43', linestyle='--', alpha=0.3)
    ax.axhline(0.7, color='#e8a33d', linestyle='--', alpha=0.3)
    ax.set_ylabel('F1-score', fontsize=12)
    ax.set_ylim(0, 1.15)
    ax.set_title(f'ความแม่นยำ (F1-score) เฟส {phase} แยกตามสถานะ\n(เขียว = แม่นมาก, ส้ม = พอใช้, แดง = ต้องปรับปรุง)', fontsize=13)
    ax.bar_label(bars, fmt='%.2f', padding=3, fontsize=12, fontweight='bold')
    ax.grid(axis='y', alpha=0.25)
    plt.xticks(rotation=20, ha='right', fontsize=11)
    plt.legend()
    plt.tight_layout()
    fname = f'f1_score_per_status_3phase_{phase}.png'
    plt.savefig(os.path.join(MODEL_FOLDER, fname), dpi=150)
    plt.show()
    f1_score_filenames.append(fname)

total_saved = len(confusion_matrix_filenames) + len(f1_score_filenames)
print(f"\n💾 บันทึกกราฟผลการทดสอบ {total_saved} รูป ลงโฟลเดอร์: {MODEL_FOLDER}")
for f in confusion_matrix_filenames + f1_score_filenames:
    print(f"   - {f}")

TEST_RESULT_FOLDER  = os.path.join(MODEL_FOLDER, 'TEST')
os.makedirs(TEST_RESULT_FOLDER, exist_ok=True)
test_result_filenames = confusion_matrix_filenames + f1_score_filenames

def move_files(filenames, dest_folder, label):
    moved, missing = [], []
    for fname in filenames:
        src = os.path.join(MODEL_FOLDER, fname)
        dst = os.path.join(dest_folder, fname)
        if os.path.exists(src):
            shutil.move(src, dst)
            moved.append(fname)
        else:
            missing.append(fname)

    print(f"✅ ย้าย{label} {len(moved)} รูป ไปไว้ที่: {dest_folder}")
    for f in moved:
        print(f"   - {f}")
    if missing:
        print(f"⚠️  ไม่พบไฟล์เหล่านี้ (อาจยังไม่ได้รันสคริปต์ที่เกี่ยวข้อง):")
        for f in missing:
            print(f"   - {f}")
    print()

move_files(test_result_filenames, TEST_RESULT_FOLDER, "กราฟผลทดสอบ")

"""#10. สร้างกราฟจากผลลัพธ์การเทรน
ใช้ df_new, feature_cols, required_features, VOLTAGE_OVER_TH,  VOLTAGE_SAG_TH, CURRENT_OVERLOAD_TH ที่มีอยู่แล้วจากสคริปต์เทรน
"""

import re
import shutil
import urllib.request
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.font_manager as fm

FONT_PATH = '/content/NotoSansThai-Regular.ttf'
try:
    if not os.path.exists(FONT_PATH):
        urllib.request.urlretrieve(
            'https://raw.githubusercontent.com/google/fonts/main/ofl/notosansthai/NotoSansThai%5Bwdth%2Cwght%5D.ttf',
            FONT_PATH
        )
    fm.fontManager.addfont(FONT_PATH)
    plt.rcParams['font.family'] = fm.FontProperties(fname=FONT_PATH).get_name()
except Exception as e:
    print(f"⚠️  โหลดฟอนต์ไทยไม่สำเร็จ ({e}) — หัวข้อกราฟภาษาไทยอาจแสดงเป็นกล่องเปล่า")

EMOJI_PATTERN = re.compile(
    "[\U0001F300-\U0001FAFF\U00002600-\U000027BF\U0001F000-\U0001F0FF]+",
    flags=re.UNICODE
)

def clean_label(text):
    return EMOJI_PATTERN.sub('', str(text)).strip()

GRAPH_FOLDER = MODEL_FOLDER  # เซฟกราฟไว้ที่เดียวกับโมเดล ปรับ path ได้ตามต้องการ

df_plot = df_new.copy()
df_plot['Timestamp'] = pd.to_datetime(df_plot['Timestamp'])
df_plot = df_plot.sort_values('Timestamp')

PHASE_COLORS = {'L1': '#2a78d6', 'L2': '#1baf7a', 'L3': '#eb6834'}

"""# แบ่งช่วงเวลากลางวัน/กลางคืน: กลางวัน 06:00-17:59, กลางคืน 18:00-05:59"""

DAY_START_HOUR = 6   # 06:00
DAY_END_HOUR   = 18  # ก่อน 18:00 (คือ 06:00-17:59 ถือเป็นกลางวัน)

PERIODS = [
    ('กลางวัน', 'day'),
    ('กลางคืน', 'night'),
]

def split_day_night(df):
    is_day = df['Timestamp'].dt.hour.between(DAY_START_HOUR, DAY_END_HOUR - 1)
    return {'day': df[is_day], 'night': df[~is_day]}

"""#
# กราฟที่ 1: แรงดันไฟฟ้าทั้ง 3 เฟส ตามเวลา + เส้นเกณฑ์ Over/Sag
#
"""

voltage_trend_filenames = []
for phase in ['L1', 'L2', 'L3']:
    by_period = split_day_night(df_plot)
    for period_th, period_en in PERIODS:
        subset = by_period[period_en]
        if subset.empty:
            print(f"⚠️  ไม่มีข้อมูลแรงดันเฟส {phase} ช่วง{period_th} ข้ามการวาดกราฟนี้")
            continue

        fig, ax = plt.subplots(figsize=(14, 5))
        ax.plot(subset['Timestamp'], subset[f'Voltage_{phase}'],
                color=PHASE_COLORS[phase], linewidth=1.2, label=phase)

        ax.axhline(VOLTAGE_OVER_TH, color='red', linestyle='--', alpha=0.6,
                   label=f'Over Voltage ({VOLTAGE_OVER_TH:.0f}V)')
        ax.axhline(VOLTAGE_SAG_TH, color='orange', linestyle='--', alpha=0.6,
                   label=f'Voltage Sag ({VOLTAGE_SAG_TH:.0f}V)')
        ax.axhline(RATED_VOLTAGE, color='gray', linestyle=':', alpha=0.5,
                   label=f'Rated ({RATED_VOLTAGE:.0f}V)')

        ax.set_ylabel('Voltage (V)')
        ax.set_title(f'แรงดันไฟฟ้าเฟส {phase} ช่วง{period_th} ตามเวลา')
        ax.legend(loc='upper left', ncol=2, fontsize=9)
        ax.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d %H:%M'))
        fig.autofmt_xdate()
        plt.tight_layout()
        fname = f'voltage_trend_{phase}_{period_en}.png'
        plt.savefig(os.path.join(GRAPH_FOLDER, fname), dpi=150)
        plt.show()
        voltage_trend_filenames.append(fname)

"""# กราฟที่ 2: กระแสไฟฟ้าทั้ง 3 เฟส ตามเวลา + เส้นเกณฑ์ Overload"""

current_trend_filenames = []
for phase in ['L1', 'L2', 'L3']:
    by_period = split_day_night(df_plot)
    for period_th, period_en in PERIODS:
        subset = by_period[period_en]
        if subset.empty:
            print(f"⚠️  ไม่มีข้อมูลกระแสเฟส {phase} ช่วง{period_th} ข้ามการวาดกราฟนี้")
            continue

        fig, ax = plt.subplots(figsize=(14, 5))
        ax.plot(subset['Timestamp'], subset[f'Current_{phase}'],
                color=PHASE_COLORS[phase], linewidth=1.2, label=phase)

        ax.axhline(CURRENT_OVERLOAD_TH, color='red', linestyle='--', alpha=0.6,
                   label=f'Overload ({CURRENT_OVERLOAD_TH:.0f}A)')
        ax.axhline(RATED_CURRENT, color='gray', linestyle=':', alpha=0.5,
                   label=f'Rated ({RATED_CURRENT:.0f}A)')

        ax.set_ylabel('Current (A)')
        ax.set_title(f'กระแสไฟฟ้าเฟส {phase} ช่วง{period_th} ตามเวลา')
        ax.legend(loc='upper left', ncol=2, fontsize=9)
        ax.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d %H:%M'))
        fig.autofmt_xdate()
        plt.tight_layout()
        fname = f'current_trend_{phase}_{period_en}.png'
        plt.savefig(os.path.join(GRAPH_FOLDER, fname), dpi=150)
        plt.show()
        current_trend_filenames.append(fname)

"""# กราฟที่ 3: Power Factor ทั้ง 3 เฟส ตามเวลา + เส้นเกณฑ์ต่ำสุด (0.85)"""

powerfactor_trend_filenames = []
for phase in ['L1', 'L2', 'L3']:
    by_period = split_day_night(df_plot)
    for period_th, period_en in PERIODS:
        subset = by_period[period_en]
        if subset.empty:
            print(f"⚠️  ไม่มีข้อมูล Power Factor เฟส {phase} ช่วง{period_th} ข้ามการวาดกราฟนี้")
            continue

        fig, ax = plt.subplots(figsize=(14, 5))
        ax.plot(subset['Timestamp'], subset[f'PowerFactor_{phase}'],
                color=PHASE_COLORS[phase], linewidth=1.2, label=phase)

        ax.axhline(0.85, color='red', linestyle='--', alpha=0.6, label='เกณฑ์ต่ำสุด (0.85)')

        ax.set_ylabel('Power Factor')
        ax.set_title(f'Power Factor เฟส {phase} ช่วง{period_th} ตามเวลา')
        ax.legend(loc='lower left', ncol=2, fontsize=9)
        ax.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d %H:%M'))
        fig.autofmt_xdate()
        plt.tight_layout()
        fname = f'powerfactor_trend_{phase}_{period_en}.png'
        plt.savefig(os.path.join(GRAPH_FOLDER, fname), dpi=150)
        plt.show()
        powerfactor_trend_filenames.append(fname)

"""# กราฟที่ 4: จำนวนสถานะที่ AI ตรวจพบ (สถานะรวม worst-case)

"""

ai_status_distribution_filenames = []
for phase in ['L1', 'L2', 'L3']:
    by_period = split_day_night(df_plot)
    for period_th, period_en in PERIODS:
        subset = by_period[period_en]
        if subset.empty:
            print(f"⚠️  ไม่มีข้อมูลสถานะ AI เฟส {phase} ช่วง{period_th} ข้ามการวาดกราฟนี้")
            continue

        status_counts = subset[f'AI_Detected_Status_{phase}'].value_counts()
        clean_labels = [clean_label(s) for s in status_counts.index]

        fig, ax = plt.subplots(figsize=(9, 5))
        bars = ax.bar(clean_labels, status_counts.values, color=PHASE_COLORS[phase])
        ax.set_ylabel('จำนวนแถว')
        ax.set_title(f'สถานะที่ AI ตรวจพบ เฟส {phase} ช่วง{period_th}')
        ax.bar_label(bars, padding=3)
        plt.xticks(rotation=20, ha='right')
        plt.tight_layout()
        fname = f'ai_status_distribution_{phase}_{period_en}.png'
        plt.savefig(os.path.join(GRAPH_FOLDER, fname), dpi=150)
        plt.show()
        ai_status_distribution_filenames.append(fname)

"""# กราฟที่ 5: จำนวนสถานะแยกรายเฟส (เทียบ L1 vs L2 vs L3)"""

status_distribution_filenames = []
for phase in ['L1', 'L2', 'L3']:
    by_period = split_day_night(df_plot)
    for period_th, period_en in PERIODS:
        subset = by_period[period_en]
        if subset.empty:
            print(f"⚠️  ไม่มีข้อมูลสถานะจริงเฟส {phase} ช่วง{period_th} ข้ามการวาดกราฟนี้")
            continue

        status_counts = subset[f'Status_{phase}'].value_counts()
        clean_labels = [clean_label(s) for s in status_counts.index]

        fig, ax = plt.subplots(figsize=(9, 5))
        bars = ax.bar(clean_labels, status_counts.values, color=PHASE_COLORS[phase])
        ax.set_ylabel('จำนวนแถว')
        ax.set_title(f'สถานะจริง (จากการวัด) เฟส {phase} ช่วง{period_th}')
        ax.bar_label(bars, padding=3)
        plt.xticks(rotation=20, ha='right')
        plt.tight_layout()
        fname = f'status_distribution_{phase}_{period_en}.png'
        plt.savefig(os.path.join(GRAPH_FOLDER, fname), dpi=150)
        plt.show()
        status_distribution_filenames.append(fname)

graph_filenames = (
    voltage_trend_filenames + current_trend_filenames + powerfactor_trend_filenames
    + ai_status_distribution_filenames + status_distribution_filenames
)

print(f"\n💾 บันทึกกราฟทั้งหมด {len(graph_filenames)} รูป (แยกรายเฟส L1/L2/L3 x กลางวัน/กลางคืน) ลงโฟลเดอร์: {GRAPH_FOLDER}")
for f in graph_filenames:
    print(f"   - {f}")


GRAPH_OUTPUT_FOLDER = os.path.join(MODEL_FOLDER, 'graphs')  # เปลี่ยนชื่อโฟลเดอร์ตรงนี้ได้ตามต้องการ
os.makedirs(GRAPH_OUTPUT_FOLDER, exist_ok=True)

moved = []
missing = []
for fname in graph_filenames:
    src = os.path.join(MODEL_FOLDER, fname)
    dst = os.path.join(GRAPH_OUTPUT_FOLDER, fname)
    if os.path.exists(src):
        shutil.move(src, dst)
        moved.append(fname)
    else:
        missing.append(fname)

print(f"✅ ย้ายกราฟ {len(moved)} รูป ไปไว้ที่: {GRAPH_OUTPUT_FOLDER}")
for f in moved:
    print(f"   - {f}")

if missing:
    print(f"\n⚠️  ไม่พบไฟล์เหล่านี้ (อาจยังไม่ได้รันสคริปต์สร้างกราฟ หรือชื่อไฟล์เปลี่ยนไป):")
    for f in missing:
        print(f"   - {f}")

"""# 11. แผนภูมิแท่งของข้อมูลชุดเดียวกับกราฟเส้น (แรงดัน/กระแส/Power Factor)
    
     - แกน x = วันที่/เวลา (Timestamp) เหมือนกราฟเส้น
     - แกน y = ค่าที่วัดได้ (Voltage / Current / PowerFactor) เหมือนกราฟเส้น
 - เส้นเกณฑ์ (threshold) และการแบ่งกลางวัน/กลางคืน เหมือนกราฟเส้นทุกประการ
    - ใช้ตัวแปรที่มีอยู่แล้ว: df_plot, split_day_night, PERIODS, PHASE_COLORS, GRAPH_FOLDER
"""

def get_day_night_spans(timestamps):
    """
    คำนวณช่วงเวลา (start, end) ของกลางวัน/กลางคืน ตลอดทั้งช่วงข้อมูล
    เพื่อเอาไปแรเงาพื้นหลังกราฟ ให้เห็นชัดว่าช่วงไหนคือกลางวัน/กลางคืน
    โดยไม่ต้องแยกกราฟออกจากกัน
    """
    if len(timestamps) == 0:
        return []

    start = timestamps.min().floor('D')
    end = timestamps.max().ceil('D') + pd.Timedelta(days=1)

    spans = []
    cur = start
    while cur < end:
        day_start = cur + pd.Timedelta(hours=DAY_START_HOUR)
        day_end = cur + pd.Timedelta(hours=DAY_END_HOUR)
        spans.append((day_start, day_end, 'day'))
        spans.append((day_end, day_start + pd.Timedelta(days=1), 'night'))
        cur += pd.Timedelta(days=1)
    return spans

DAY_NIGHT_BG_COLORS = {'day': '#ffe6a3', 'night': '#b7c6e6'}

def plot_bar_trend(value_col_template, ylabel, title_prefix, file_prefix,
                    threshold_lines, out_folder, legend_loc='upper left'):
    """
    วาดแผนภูมิแท่งของค่าที่วัดได้ตามเวลา (x=Timestamp, y=ค่าที่วัด)
    กลางวัน/กลางคืนอยู่ในกราฟเดียวกัน แต่แรเงาพื้นหลังแยกให้เห็นชัดเจน
    (เหลืองอ่อน = กลางวัน 06:00-17:59, ฟ้าอ่อน = กลางคืน 18:00-05:59)
    threshold_lines: list ของ (ค่า, สี, label) สำหรับวาดเส้นเกณฑ์ประกอบ
    """
    saved_filenames = []
    for phase in ['L1', 'L2', 'L3']:
        col = value_col_template.format(phase=phase)
        subset = df_plot[['Timestamp', col]].dropna()
        if subset.empty:
            print(f"⚠️  ไม่มีข้อมูล {col} ข้ามการวาดกราฟแท่งนี้")
            continue

        fig, ax = plt.subplots(figsize=(16, 5))

        # แรเงาพื้นหลังกลางวัน/กลางคืนตลอดทั้งกราฟ ก่อนวาดแท่งข้อมูล
        spans = get_day_night_spans(subset['Timestamp'])
        seen_period_label = set()
        for span_start, span_end, period_en in spans:
            label = None
            if period_en not in seen_period_label:
                label = 'กลางวัน (06:00-17:59)' if period_en == 'day' else 'กลางคืน (18:00-05:59)'
                seen_period_label.add(period_en)
            ax.axvspan(span_start, span_end, color=DAY_NIGHT_BG_COLORS[period_en],
                       alpha=0.6, zorder=0, label=label)

        # กราฟเส้น + แรเงาพื้นที่ใต้เส้น (Area chart) แบบเดียวกับแดชบอร์ดตัวอย่าง
        color = PHASE_COLORS[phase]
        ax.fill_between(subset['Timestamp'], subset[col], color=color, alpha=0.25, zorder=2)
        ax.plot(subset['Timestamp'], subset[col], color=color, linewidth=1.8, label=phase, zorder=3)

        for th_value, th_color, th_label in threshold_lines:
            ax.axhline(th_value, color=th_color, linestyle='--', alpha=0.7, zorder=3, label=th_label)

        # จุดค่าสูงสุด (peak) พร้อมกล่อง tooltip ชี้ค่า/เวลา เหมือนแดชบอร์ดตัวอย่าง
        max_idx = subset[col].idxmax()
        max_point = subset.loc[max_idx]
        ax.axvline(max_point['Timestamp'], color='#c0392b', linewidth=0.8, alpha=0.5, zorder=1)
        ax.scatter([max_point['Timestamp']], [max_point[col]], color=color, s=70,
                   edgecolor='white', linewidth=1.5, zorder=5)
        tooltip_text = (f"{max_point['Timestamp'].strftime('%Y-%m-%d %H:%M:%S')}\n"
                         f"{title_prefix} ({phase}): {max_point[col]:.2f}")
        ax.annotate(
            tooltip_text,
            xy=(max_point['Timestamp'], max_point[col]),
            xytext=(15, 12), textcoords='offset points',
            fontsize=9, color='white', linespacing=1.6,
            bbox=dict(boxstyle='round,pad=0.5', fc='#333333', ec='none', alpha=0.9),
            zorder=6,
        )

        # สรุป min/max มุมล่างขวา เหมือนแดชบอร์ดตัวอย่าง
        min_val = subset[col].min()
        max_val = subset[col].max()
        ax.text(0.90, -0.17, 'min', transform=ax.transAxes, ha='center', va='top',
                fontsize=10, fontweight='bold', color='#e8833d')
        ax.text(0.90, -0.24, f'{min_val:.2f}', transform=ax.transAxes, ha='center', va='top', fontsize=10)
        ax.text(0.98, -0.17, 'max', transform=ax.transAxes, ha='center', va='top',
                fontsize=10, fontweight='bold', color='#e8833d')
        ax.text(0.98, -0.24, f'{max_val:.2f}', transform=ax.transAxes, ha='center', va='top', fontsize=10)

        ax.set_xlim(subset['Timestamp'].min() - pd.Timedelta(hours=1),
                    subset['Timestamp'].max() + pd.Timedelta(hours=1))
        ax.set_ylabel(ylabel)
        ax.set_title(f'{title_prefix} เฟส {phase} ตามเวลา (Area Chart, กลางวัน/กลางคืน)')
        ax.legend(loc=legend_loc, ncol=2, fontsize=9)
        ax.xaxis.set_major_formatter(mdates.DateFormatter('%m-%d %H:%M'))
        fig.autofmt_xdate()
        plt.tight_layout()

        fname = f'{file_prefix}_{phase}_bar.png'
        plt.savefig(os.path.join(out_folder, fname), dpi=150)
        plt.show()
        saved_filenames.append(fname)

    return saved_filenames

"""# แผนภูมิแท่งที่ 1: แรงดันไฟฟ้า"""

voltage_bar_filenames = plot_bar_trend(
    'Voltage_{phase}',
    'Voltage (V)',
    'แรงดันไฟฟ้า',
    'voltage_trend',
    [
        (VOLTAGE_OVER_TH, 'red', f'Over Voltage ({VOLTAGE_OVER_TH:.0f}V)'),
        (VOLTAGE_SAG_TH, 'orange', f'Voltage Sag ({VOLTAGE_SAG_TH:.0f}V)'),
        (RATED_VOLTAGE, 'gray', f'Rated ({RATED_VOLTAGE:.0f}V)'),
    ],
    GRAPH_FOLDER,
)

"""# แผนภูมิแท่งที่ 2: กระแสไฟฟ้า"""

current_bar_filenames = plot_bar_trend(
    'Current_{phase}',
    'Current (A)',
    'กระแสไฟฟ้า',
    'current_trend',
    [
        (CURRENT_OVERLOAD_TH, 'red', f'Overload ({CURRENT_OVERLOAD_TH:.0f}A)'),
        (RATED_CURRENT, 'gray', f'Rated ({RATED_CURRENT:.0f}A)'),
    ],
    GRAPH_FOLDER,
)

"""# แผนภูมิแท่งที่ 3: Power Factor"""

powerfactor_bar_filenames = plot_bar_trend(
    'PowerFactor_{phase}',
    'Power Factor',
    'Power Factor',
    'powerfactor_trend',
    [
        (0.85, 'red', 'เกณฑ์ต่ำสุด (0.85)'),
    ],
    GRAPH_FOLDER,
    legend_loc='lower left',
)

bar_trend_filenames = voltage_bar_filenames + current_bar_filenames + powerfactor_bar_filenames

print(f"\n💾 บันทึกแผนภูมิแท่ง {len(bar_trend_filenames)} รูป (แยกรายเฟส L1/L2/L3, กลางวัน/กลางคืนอยู่ในกราฟเดียวกันแบบแรเงาแยก) ลงโฟลเดอร์: {GRAPH_FOLDER}")
for f in bar_trend_filenames:
    print(f"   - {f}")

bar_moved = []
bar_missing = []
for fname in bar_trend_filenames:
    src = os.path.join(GRAPH_FOLDER, fname)
    dst = os.path.join(GRAPH_OUTPUT_FOLDER, fname)
    if os.path.exists(src):
        shutil.move(src, dst)
        bar_moved.append(fname)
    else:
        bar_missing.append(fname)

print(f"✅ ย้ายแผนภูมิแท่ง {len(bar_moved)} รูป ไปไว้ที่: {GRAPH_OUTPUT_FOLDER}")
for f in bar_moved:
    print(f"   - {f}")

if bar_missing:
    print(f"\n⚠️  ไม่พบไฟล์เหล่านี้ (อาจยังไม่ได้รันโค้ดส่วนแผนภูมิแท่ง):")
    for f in bar_missing:
        print(f"   - {f}")